#有层次可以继承的文件格式
server:
  port: 80
  servlet:
    context-path: /boot

zwj:
  root:
    username: root
    password: 123456
  info:
    name: zwj
    age: 18
  gfs: #集合
    - dda
    - adf
    - fsa

cyl:
  user:
    username: root
    password:
    gfs:
      - wdf
      - fk
      - tk

spring:
  profiles:
    active: test,dev  #激活
